### ISSUE TITLE
SMTP lib even exists?

### ISSUE THREAD

**Issue by 555Russich** [mishakorzik/Email-Spammer#12]
`$ python3.9 -m venv venv`
`$ source venv/bin/activate`
`$ pip install requests smtp`

> Collecting requests
>   Using cached requests-2.28.2-py3-none-any.whl (62 kB)
> ERROR: Could not find a version that satisfies the requirement smtp (from versions: none)
> ERROR: No matching distribution found for smtp

which version of python is required? I can't even find `smtp` lib on pypi.org ...
btw smtplib is builtin module

**Comment by mishakorzik** [comment]
Yes its a system python library

**Comment by mishakorzik** [comment]
Yes its a system python library

**Comment by 555Russich** [comment]
> Yes its a system python library

`smptlib` is builtin module, not `smtp`. You should remove this line from `README.md`: 

> pip3 install smtp

**Comment by mishakorzik** [comment]
Okay
