### ISSUE TITLE
Very cringe and skidworthy

### ISSUE THREAD

**Issue by TruncatedDinosour** [mishakorzik/Email-Spammer#3]
Github, please stop recommending this garbage to me, i cannot, this is horrible trash, just because i know python doesn't mean i want to be surrounded by these skids

**Comment by TruncatedDinosour** [comment]
lmfao

**Comment by PhantomRex123** [comment]
@TruncatedDinosour soo true

**Comment by TheChungusMuncher** [comment]
this repo is so r/masterhacker worthy

**Comment by byCRXHIT** [comment]
> this repo is so r/masterhacker worthy

true 💀

**Comment by mishakorzik** [comment]
> Github, please stop recommending this garbage to me, i cannot, this is horrible trash, just because i know python doesn't mean i want to be surrounded by these skids

it's not trash

**Comment by TruncatedDinosour** [comment]
> > Github, please stop recommending this garbage to me, i cannot, this is horrible trash, just because i know python doesn't mean i want to be surrounded by these skids
> 
> it's not trash

it is.

**Comment by Locksdsc** [comment]
lmao
