### ISSUE TITLE
RuntimeError: Bad magic number in .pyc file

### ISSUE THREAD

**Issue by NZNBS** [mishakorzik/Email-Spammer#4]
System: Kali Linux
Arm: 64
Python: 2.7.18
`python custom_spam.py                                                                   130 ⨯ 2 ⚙
  File "src/version.py", line 25
    print(G + '[>]' + C + ' Checking for system configurations....', end='')
                                                                        ^
SyntaxError: invalid syntax
RuntimeError: Bad magic number in .pyc file`

**Comment by Gomaxaxx** [comment]
same issue

**Comment by mishakorzik** [comment]
you have a problem because Kali Linux is not supported on email-spammer.  I recommend downloading termux to your phone and do it all there.

**Comment by mishakorzik** [comment]
Or try running on python3.

**Comment by vstyler96** [comment]
This should be open.  It's not resolved.

**Comment by mishakorzik** [comment]
Use python3 for Email-Spammer.

**Comment by vstyler96** [comment]
> Use python3 for Email-Spammer.

No, it doesn't work with python3 nor on Termux

**Comment by mishakorzik** [comment]
Use python 3.10 or python3.7

**Comment by goossensth** [comment]
Don't work on Python3, same issue

**Comment by Legendssssok** [comment]
can you make like speed x tbomb

**Comment by mishakorzik** [comment]
Fixed.
