### ISSUE TITLE
File Error

### ISSUE THREAD

**Issue by Narcotica** [mishakorzik/Email-Spammer#5]
File "src/serv.py", line 5
    Z♂e
     ^
SyntaxError: invalid syntax

**Comment by Twinsrainbows1** [comment]
Think this just cap I got the same

**Comment by 1804909625** [comment]
My file serv Py is even garbled. I tried GBK and UTF-8, but they are still invalid. What's your code

**Comment by v1s1t0r999** [comment]
serv.py is raw binary.

**Comment by v1s1t0r999** [comment]
@mishakorzik Bro I can see your api key and email id and stuff. Also, are u using .pyc binaries to hide codes?? Like jus dont upload on github lmao

**Comment by byCRXHIT** [comment]
this guy is just a pure genius
![genius](https://user-images.githubusercontent.com/70042525/182046038-e5ff989d-6f41-49a9-8f82-2338f4f08a9e.png)

**Comment by mishakorzik** [comment]
Fixed
